# Generated by Django 2.2.3 on 2019-08-06 09:01

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('info', '0013_auto_20181112_1846'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
