# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mymain.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainscreen(object):
    def setupUi(self, mainscreen):
        mainscreen.setObjectName("mainscreen")
        mainscreen.resize(707, 554)
        mainscreen.setStyleSheet("background-color: rgb(203, 203, 203);")
        self.centralwidget = QtWidgets.QWidget(mainscreen)
        self.centralwidget.setObjectName("centralwidget")
        self.news = QtWidgets.QPushButton(self.centralwidget)
        self.news.setGeometry(QtCore.QRect(-10, 120, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(14)
        self.news.setFont(font)
        self.news.setFlat(True)
        self.news.setObjectName("news")
        self.google = QtWidgets.QPushButton(self.centralwidget)
        self.google.setGeometry(QtCore.QRect(10, 200, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(14)
        self.google.setFont(font)
        self.google.setFlat(True)
        self.google.setObjectName("google")
        self.youtube = QtWidgets.QPushButton(self.centralwidget)
        self.youtube.setGeometry(QtCore.QRect(10, 360, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(14)
        self.youtube.setFont(font)
        self.youtube.setAutoDefault(False)
        self.youtube.setFlat(True)
        self.youtube.setObjectName("youtube")
        self.weatherbtn = QtWidgets.QPushButton(self.centralwidget)
        self.weatherbtn.setGeometry(QtCore.QRect(430, 110, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(14)
        self.weatherbtn.setFont(font)
        self.weatherbtn.setFlat(True)
        self.weatherbtn.setObjectName("weatherbtn")
        self.quora = QtWidgets.QPushButton(self.centralwidget)
        self.quora.setGeometry(QtCore.QRect(420, 190, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(14)
        self.quora.setFont(font)
        self.quora.setFlat(True)
        self.quora.setObjectName("quora")
        self.exitbutton = QtWidgets.QPushButton(self.centralwidget)
        self.exitbutton.setGeometry(QtCore.QRect(230, 470, 261, 51))
        self.exitbutton.setStyleSheet("background-color: rgb(85, 239, 241);\n"
"font: 16pt \"Ravie\";")
        self.exitbutton.setFlat(True)
        self.exitbutton.setObjectName("exitbutton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(-10, 0, 731, 541))
        self.label_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../IMAGES/stains_liquid_paint_145278_3840x2160.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.presstospeak = QtWidgets.QPushButton(self.centralwidget)
        self.presstospeak.setGeometry(QtCore.QRect(210, 60, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(7)
        self.presstospeak.setFont(font)
        self.presstospeak.setStyleSheet("font: 63 italic 16pt \"Lucida Bright\";")
        self.presstospeak.setFlat(True)
        self.presstospeak.setObjectName("presstospeak")
        self.applebtn = QtWidgets.QPushButton(self.centralwidget)
        self.applebtn.setGeometry(QtCore.QRect(40, 280, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(14)
        self.applebtn.setFont(font)
        self.applebtn.setFlat(True)
        self.applebtn.setObjectName("applebtn")
        self.flipkart = QtWidgets.QPushButton(self.centralwidget)
        self.flipkart.setGeometry(QtCore.QRect(430, 270, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(14)
        self.flipkart.setFont(font)
        self.flipkart.setFlat(True)
        self.flipkart.setObjectName("flipkart")
        self.gmail = QtWidgets.QPushButton(self.centralwidget)
        self.gmail.setGeometry(QtCore.QRect(410, 350, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(14)
        self.gmail.setFont(font)
        self.gmail.setFlat(True)
        self.gmail.setObjectName("gmail")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 191, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(510, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3.raise_()
        self.news.raise_()
        self.google.raise_()
        self.youtube.raise_()
        self.weatherbtn.raise_()
        self.quora.raise_()
        self.exitbutton.raise_()
        self.presstospeak.raise_()
        self.applebtn.raise_()
        self.flipkart.raise_()
        self.gmail.raise_()
        self.label.raise_()
        self.label_2.raise_()
        mainscreen.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(mainscreen)
        self.statusBar.setObjectName("statusBar")
        mainscreen.setStatusBar(self.statusBar)
        self.actionExit = QtWidgets.QAction(mainscreen)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(mainscreen)
        QtCore.QMetaObject.connectSlotsByName(mainscreen)

    def retranslateUi(self, mainscreen):
        _translate = QtCore.QCoreApplication.translate
        mainscreen.setWindowTitle(_translate("mainscreen", "mainwindow"))
        self.news.setText(_translate("mainscreen", "READ NEWS"))
        self.google.setText(_translate("mainscreen", "OPEN GOOGLE"))
        self.youtube.setText(_translate("mainscreen", "OPEN YOUTUBE"))
        self.weatherbtn.setText(_translate("mainscreen", "WEATHER REPORT"))
        self.quora.setText(_translate("mainscreen", "OPEN QUORA"))
        self.exitbutton.setText(_translate("mainscreen", "PRESS TO EXIT!!!!"))
        self.presstospeak.setText(_translate("mainscreen", "PRESS TO SPEAK"))
        self.applebtn.setText(_translate("mainscreen", "OPEN APPLE.COM"))
        self.flipkart.setText(_translate("mainscreen", "OPEN FLIPKART"))
        self.gmail.setText(_translate("mainscreen", "OPEN GMAIL"))
        self.actionExit.setText(_translate("mainscreen", "Exit!"))
